name: securityvision-core

on:
  workflow_dispatch:
    branches:
    - dev
    inputs:    
      deleteM2:
        description: 'If you want to skip m2 folder deletion then make sure to provide input has true'
        required: true
        default : 'false'
        type: choice
        options:
          - false
          - true
      runcodeScan:
        description: 'If you want to skip Mend, Coverity and Sonar Scanning then make sure to provide input has true'
        required: true
        default : 'false'
        type: choice
        options:
          - false
          - true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4


        


   