name: securityvision-core

on:
  workflow_dispatch:
    inputs:    
      deleteM2:
        description: 'If you want to skip m2 folder deletion then make sure to provide input has true'
        required: true
        default : 'false'
        type: choice
        options:
          - fs
          - ts
      runcodeScan:
        description: 'If you want to skip Mend, Coverity and Sonar Scanning then make sure to provide input has true'
        required: true
        default : 'false'
        type: choice
        options:
          - f
          - t


        


   
